### ISSUE TITLE
TypeError: 'staticmethod' object is not callable

### ISSUE THREAD

**Issue by Brblol** [jaketae/storyteller#19]
_$storyteller --writer_prompt "The ravenous cat, driven by an insatiable craving for tuna, devised a daring plan to break into the local fish market's coveted tuna reserve."_
Traceback (most recent call last):
  File "/home/m/.local/bin/storyteller", line 5, in <module>
    from storyteller.cli import main
  File "/home/m/.local/lib/python3.8/site-packages/storyteller/__init__.py", line 3, in <module>
    from storyteller.config import StoryTellerConfig
  File "/home/m/.local/lib/python3.8/site-packages/storyteller/config.py", line 46, in <module>
    class StoryTellerConfigArgparseHelpText:
  File "/home/m/.local/lib/python3.8/site-packages/storyteller/config.py", line 53, in StoryTellerConfigArgparseHelpText
    _get_dataclass_var_name_from_f_string_eq(
TypeError: 'staticmethod' object is not callable

My system:
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

Python 3.8.10

**Comment by jaketae** [comment]
Hi, thanks for the issue, and apologies for the delay in response.

Is this on the latest main branch or through `pip install`? I will take a look at it in the new couple of weeks, as soon as I have bandwidth. Thanks!
